version: "3"
services:
  database:
    image: postgres
    container_name: database
    ports:
      - 2345:5432
    env_file:
      - .env.test

  app_node:
    build: .
    container_name: node_app
    ports:
      - 80:5000
    env_file:
      - .env
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run test"
    depends_on:
      - database

volumes:
  database_volume:
