version: "3"
services:
  database:
    image: postgres
    container_name: database
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/postgressql/data

  app_node:
    build: .
    container_name: node_app
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - database

volumes:
  database_volume:
